name: Jon Williams
favicon: null
layout_spectrum: 0.5780561
typography_spectrum: 0.1200102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76209570-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2948325
  lightness: 0.4988143
  saturation: 0.273916
  rhythmicContrast: 0.7641557
purpose: []
