name: Jon Williams
favicon: null
layout_spectrum: 0.21773
typography_spectrum: 0.89458
title: Jon Williams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76209570-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff630f'
    - '#ffffff'
    - '#848589'
    - '#003b5b'
    - '#1187bc'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
